version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:lts
    working_directory: ~/repo

jobs:
  cypress-tests:
    executor: node
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Run Cypress tests
          command: npm run test:cypress
      - store_test_results:
          path: cypress/results

  playwright-tests:
    executor: node
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Install Playwright browsers
          command: npx playwright install --with-deps
      - run:
          name: Run Playwright tests
          command: npm run test:playwright:ci
      - store_test_results:
          path: test-results

workflows:
  run-tests:
    triggers:
      - schedule:
          cron: '0 0 1 * *'
          filters:
            branches:
              only:
                - main
    jobs:
      - cypress-tests
      - playwright-tests
