version: 2.1

jobs:
  cypress-run:
    docker:
      - image: cypress/base:14.5.0
    steps:
      - checkout
      - run:
          name: Setup Node.js (use preinstalled from image)
          command: node -v
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run Cypress tests
          command: npm run test:cypress
          environment:
            CYPRESS_baseUrl: 'https://www.saucedemo.com'

workflows:
  version: 2
  cypress-tests:
    triggers:
      - schedule:
          cron: '0 0 1 * *'
          filters:
            branches:
              only:
                - main
    jobs:
      - cypress-run:
          filters:
            branches:
              only:
                - main
