version: 2.1

executors:
  cypress:
    docker:
      - image: cypress/included:14.5.0
    working_directory: ~/repo

  playwright:
    docker:
      - image: mcr.microsoft.com/playwright:focal
    working_directory: ~/repo

jobs:
  cypress-tests:
    executor: cypress
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Run Cypress tests
          command: npm run test:cypress
      - store_test_results:
          path: cypress/results

  playwright-tests:
    executor: playwright
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Install Playwright browsers
          command: npx playwright install --with-deps
      - run:
          name: Run Playwright tests
          command: npm run test:playwright:ci
      - store_test_results:
          path: test-results

workflows:
  run-tests:
    jobs:
      - cypress-tests
      - playwright-tests
