version: 2.1

jobs:
  cypress-run:
    docker:
      - image: cypress/base:14.5.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run Cypress tests
          command: npx cypress run --browser chrome

workflows:
  version: 2
  test:
    jobs:
      - cypress-run
