name: Run Cypress Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 1 * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm test:cypress
        env:
          CYPRESS_baseUrl: 'https://www.saucedemo.com'
